<?php
/**
 * GET /api/preview.php?token=...
 *
 * Serves a watermarked, page-limited preview PDF. The token (signed,
 * short-lived — see sign_token()/verify_token() in functions.php) is
 * generated by student/preview.php; this endpoint additionally
 * requires a live, matching student session, so a leaked/shared
 * preview link alone is not enough to view the document.
 */
declare(strict_types=1);

require_once __DIR__ . '/_bootstrap.php';
require_once __DIR__ . '/../includes/watermark.php';

$student = current_student();
if (!$student) {
    http_response_code(401);
    die('Please sign in to view this preview.');
}

$token = (string) ($_GET['token'] ?? '');
$payload = verify_token($token);

if (!$payload || ($payload['type'] ?? '') !== 'preview' || (int) ($payload['student_id'] ?? 0) !== (int) $student['id']) {
    http_response_code(403);
    die('This preview link is invalid or has expired. Please go back and try again.');
}

$documentId = (int) $payload['document_id'];
$stmt = get_db()->prepare("SELECT * FROM documents WHERE id = :id AND status = 'ACTIVE'");
$stmt->execute(['id' => $documentId]);
$document = $stmt->fetch();

if (!$document) {
    http_response_code(404);
    die('Document not found.');
}

try {
    $previewPath = ensure_preview($document, $student['email']);
} catch (\Throwable $e) {
    error_log('NOTE BANK preview generation failed: ' . $e->getMessage());
    http_response_code(503);
    if (!IS_PRODUCTION) {
        // Local/dev only — show the real cause (e.g. "pdftoppm is not
        // installed") instead of a generic message, so this is fast to
        // diagnose instead of a silent dead end. Never shown once
        // APP_ENV=production.
        die('Preview generation failed: ' . htmlspecialchars($e->getMessage()));
    }
    die('Preview is temporarily unavailable. Please try again shortly.');
}

header('Content-Type: application/pdf');
header('Content-Length: ' . filesize($previewPath));
header('Content-Disposition: inline; filename="preview.pdf"');
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: SAMEORIGIN');
header('Cache-Control: private, no-store, no-cache, must-revalidate');
header('Pragma: no-cache');
readfile($previewPath);
